dist: focal
language: csharp
mono: none
dotnet: 5.0

before_install: sudo apt-get install dotnet-sdk-3.1

jobs:
  include:
    - stage: test
      script:
      - dotnet restore
      - dotnet test -f netcoreapp3.1
      script:
      - dotnet restore
      - dotnet test -f net50
    - stage: deploy
      if: branch = main AND tag IS present AND tag =~ /^\d{1,4}.\d{1,4}.\d{1,4}/ AND type = push
      script:
      - dotnet pack /p:PackageVersion=$TRAVIS_TAG

notifications:
  email: false
